/**
 * 2026-10-03 博客收缩:让 Google 一眼看出这个站是做什么的。
 *
 * 依据是对全部 467 篇的逐篇审计(Codex 按统一标准打分 + 人工校准 + GSC 近 90 天逐页数据):
 * 第一轮电商模板 200 篇大部分写的是开店操作、供货商、各人群找副业、"订阅 YouTube 要不要钱"这类
 * 与"有收入证据的创业项目"无关的话题,90 天合计 4 次点击,却在稀释整站的主题信号。
 *
 * - GONE:主题不属于本站、且 90 天点击 ≤1 的文章 → proxy 返回 410(比 404 更快被移出索引)
 * - REDIRECTS:与某篇保留文章同一意图的重复页 → next.config 308 到保留页(把它们的信号合到一篇上)
 * - REMOVED_CATEGORIES:文章已全部删除/合并的分类枢纽页 → 410
 *
 * 内容文件已从 src/content/blog 删除(git 历史里还在)。站内正文里指向这些地址的链接已改写,
 * Markdown 渲染层另有兜底:指向不存在文章的站内链接降级为纯文本,指向合并页的直接改指最终地址。
 * 2026-10-07 第二轮:只动 8 月 1 日及更早发布、已有两个多月却 90 天几乎零点击的老页(九月以后发布的一律不动)。
 * 删掉整类的电商(store-economics)与泛小生意收入(what-it-really-pays),SaaS 财务词典、泛副业/被动收入、
 * 博主/联盟入门、单词释义页;同一意图的重复页 308 到保留页。72 篇里 21 篇 410、51 篇合并,90 天合计 3 次点击。
 *
 * 以后新写文章不要再碰这些选题;要恢复某篇,先从这里移除再恢复文件。
 */

export const RETIRED_GONE: readonly string[] = [
  "/blog/build-and-ship/boilerplate-examples",
  "/blog/build-and-ship/boilerplate-meaning",
  "/blog/build-and-ship/saas-boilerplate-that-shipped",
  "/blog/digital-products/best-selling-items-on-etsy",
  "/blog/digital-products/digital-downloads-app-for-shopify",
  "/blog/digital-products/dropshipping-course",
  "/blog/digital-products/high-ticket-dropshipping",
  "/blog/digital-products/online-courses-for-stay-at-home-moms",
  "/blog/digital-products/shopify-templates",
  "/blog/digital-products/trending-dropshipping-product",
  "/blog/launch-and-growth/product-hunt-launch",
  "/blog/launch-and-growth/saas-founder",
  "/blog/launch-and-growth/saas-marketing",
  "/blog/launch-and-growth/saas-valuation-multiples",
  "/blog/launch-and-growth/sell-a-saas",
  "/blog/launch-and-growth/seo-for-saas",
  "/blog/physical-products/candles-dropshipping",
  "/blog/physical-products/dropshipping-clothing",
  "/blog/physical-products/dropshipping-clothing-suppliers",
  "/blog/physical-products/dropshipping-furniture",
  "/blog/physical-products/dropshipping-jewellery",
  "/blog/physical-products/dropshipping-jewelry",
  "/blog/physical-products/dropshipping-pet-supplies",
  "/blog/physical-products/etsy-shop-vintage",
  "/blog/physical-products/home-decor-dropshipping",
  "/blog/physical-products/home-decor-shopify",
  "/blog/physical-products/pet-products-dropshipping",
  "/blog/physical-products/pet-sitting-side-hustle",
  "/blog/physical-products/side-hustle-auctions-and-thrift",
  "/blog/platform-guides/amazon-dropshipping-supplier",
  "/blog/platform-guides/american-suppliers-for-dropshipping",
  "/blog/platform-guides/dropshipping-supplier-for-ebay",
  "/blog/platform-guides/etsy-shop-setup",
  "/blog/platform-guides/free-dropshipping-suppliers",
  "/blog/platform-guides/how-do-you-close-an-etsy-shop",
  "/blog/platform-guides/how-does-selling-on-ebay-work",
  "/blog/platform-guides/how-does-shopify-work",
  "/blog/platform-guides/how-to-make-money-online-as-a-teenager",
  "/blog/platform-guides/how-to-make-money-online-with-money",
  "/blog/platform-guides/how-to-sell-on-depop",
  "/blog/platform-guides/how-to-sell-on-ebay",
  "/blog/platform-guides/how-to-sell-things-on-etsy",
  "/blog/platform-guides/how-to-start-a-dropshipping-business",
  "/blog/platform-guides/how-to-start-dropshipping-for-free",
  "/blog/platform-guides/how-to-start-selling-on-ebay",
  "/blog/platform-guides/shopify-dropshipping-suppliers",
  "/blog/platform-guides/suppliers-dropshipping",
  "/blog/platform-guides/woocommerce-dropshipping-supplier",
  "/blog/print-on-demand/amazon-print-on-demand",
  "/blog/print-on-demand/canva-for-print-on-demand",
  "/blog/print-on-demand/contrado-print-on-demand",
  "/blog/print-on-demand/gelato-print-on-demand",
  "/blog/print-on-demand/gooten-print-on-demand",
  "/blog/print-on-demand/phone-case-print-on-demand",
  "/blog/print-on-demand/poster-print-on-demand",
  "/blog/print-on-demand/print-on-demand-art-prints",
  "/blog/print-on-demand/print-on-demand-caps",
  "/blog/print-on-demand/print-on-demand-colouring-books",
  "/blog/print-on-demand/print-on-demand-etsy",
  "/blog/print-on-demand/print-on-demand-fabric",
  "/blog/print-on-demand/print-on-demand-greeting-cards",
  "/blog/print-on-demand/print-on-demand-marketplace",
  "/blog/print-on-demand/print-on-demand-services",
  "/blog/print-on-demand/print-on-demand-services-for-books",
  "/blog/print-on-demand/print-on-demand-shirts",
  "/blog/print-on-demand/print-on-demand-sticker",
  "/blog/print-on-demand/print-on-demand-wallpaper",
  "/blog/print-on-demand/printful-print-on-demand",
  "/blog/print-on-demand/printful-print-on-demand-fulfillment-at-westlake",
  "/blog/print-on-demand/shopify-print-on-demand-app",
  "/blog/print-on-demand/what-is-print-on-demand",
  "/blog/revenue-reality/50-passive-income-ideas",
  "/blog/revenue-reality/amazon-self-publishing-cost",
  "/blog/revenue-reality/best-passive-income-businesses",
  "/blog/revenue-reality/best-passive-income-streams",
  "/blog/revenue-reality/does-it-cost-money-to-subscribe-to-a-youtube-channel",
  "/blog/revenue-reality/etsy-calculator",
  "/blog/revenue-reality/etsy-fee-calculator",
  "/blog/revenue-reality/etsy-shop-cost",
  "/blog/revenue-reality/etsy-shop-setup-fee",
  "/blog/revenue-reality/good-passive-income-streams",
  "/blog/revenue-reality/how-much-does-it-cost-to-have-etsy-shop",
  "/blog/revenue-reality/how-much-does-self-publishing-a-book-cost",
  "/blog/revenue-reality/how-much-is-an-etsy-shop-per-month",
  "/blog/revenue-reality/how-much-is-shopify",
  "/blog/revenue-reality/how-to-make-money-on-etsy",
  "/blog/revenue-reality/online-course-for-passive-income",
  "/blog/revenue-reality/passive-income-businesses-for-sale",
  "/blog/revenue-reality/passive-income-ideas-for-young-adults",
  "/blog/revenue-reality/passive-income-on-etsy",
  "/blog/revenue-reality/passive-income-side-hustle",
  "/blog/revenue-reality/profitable-niches-for-dropshipping",
  "/blog/revenue-reality/shipping-calculator-etsy",
  "/blog/risks-and-rules/dropshipping-is-dead",
  "/blog/risks-and-rules/dropshipping-is-it-worth-it",
  "/blog/risks-and-rules/dropshipping-shipping-policy",
  "/blog/risks-and-rules/is-amazon-dropshipping-legal",
  "/blog/risks-and-rules/is-dropshipping-legal",
  "/blog/risks-and-rules/is-dropshipping-legit",
  "/blog/risks-and-rules/is-dropshipping-still-profitable-in-2026",
  "/blog/risks-and-rules/is-etsy-legit",
  "/blog/risks-and-rules/is-etsy-plus-worth-it",
  "/blog/risks-and-rules/is-etsy-safe",
  "/blog/risks-and-rules/is-shopify-legit",
  "/blog/risks-and-rules/is-shopify-worth-it",
  "/blog/risks-and-rules/is-upwork-worth-it",
  "/blog/risks-and-rules/pros-and-cons-of-dropshipping",
  "/blog/risks-and-rules/selling-on-ebay-is-it-worth-it",
  "/blog/risks-and-rules/shopify-shipping-policy-example",
  "/blog/saas-metrics/burn-rate",
  "/blog/saas-metrics/startup-runway",
  "/blog/saas-metrics/what-is-saas-sales",
  "/blog/shop-operations/advertising-dropshipping",
  "/blog/shop-operations/dropshipping-marketing-strategies",
  "/blog/shop-operations/etsy-seo-services",
  "/blog/shop-operations/etsy-shop-discount-codes",
  "/blog/shop-operations/etsy-shop-name-generator",
  "/blog/shop-operations/etsy-shop-names",
  "/blog/shop-operations/facebook-dropshipping-ads",
  "/blog/shop-operations/how-does-tiktok-shop-work",
  "/blog/shop-operations/how-to-change-etsy-shop-name",
  "/blog/shop-operations/how-to-make-money-online-instagram",
  "/blog/shop-operations/how-to-make-money-online-pinterest",
  "/blog/shop-operations/how-to-sell-on-tiktok-shop",
  "/blog/shop-operations/how-to-set-up-tiktok-shop",
  "/blog/shop-operations/online-marketing-tools-for-small-business",
  "/blog/shop-operations/photography-side-hustle",
  "/blog/shop-operations/shop-announcement-etsy-example",
  "/blog/shop-operations/shop-coupon-code-etsy",
  "/blog/shop-operations/shopify-affiliate-marketing",
  "/blog/shop-operations/shopify-business-name-generator",
  "/blog/shop-operations/shopify-logo-maker",
  "/blog/shop-operations/shopify-seo-agency",
  "/blog/side-income/best-passive-income-ideas",
  "/blog/side-income/creating-passive-income-online",
  "/blog/side-income/how-to-make-side-income",
  "/blog/side-income/passive-income-business-ideas",
  "/blog/side-income/passive-income-side-hustles",
  "/blog/start-cheap/dropshipping-for-free",
  "/blog/start-cheap/fast-make-money-online",
  "/blog/start-cheap/fast-ways-to-make-money-online",
  "/blog/start-cheap/free-dropshipping-account",
  "/blog/start-cheap/free-dropshipping-website",
  "/blog/start-cheap/free-make-money-online",
  "/blog/start-cheap/free-self-publishing-platforms",
  "/blog/start-cheap/free-shopify-themes",
  "/blog/start-cheap/shopify-alternatives-free",
  "/blog/start-cheap/shopify-free-trial",
  "/blog/start-cheap/side-hustle-from-home-no-experience",
  "/blog/start-cheap/side-hustle-jobs-from-home",
  "/blog/start-cheap/side-hustle-jobs-work-from-home",
  "/blog/startup-ideas/best-dropshipping-websites",
  "/blog/startup-ideas/best-platform-for-self-publishing",
  "/blog/startup-ideas/best-rated-self-publishing-company",
  "/blog/startup-ideas/best-self-publishing-companies",
  "/blog/startup-ideas/best-site-to-make-money-online",
  "/blog/startup-ideas/ideas-for-etsy-shop",
  "/blog/startup-ideas/way-to-make-money-online",
  "/blog/store-economics/how-much-do-dropshippers-make",
  "/blog/store-economics/how-much-does-an-etsy-shop-cost",
  "/blog/store-economics/how-much-does-dropshipping-make",
  "/blog/store-economics/how-much-does-etsy-take-from-sales",
  "/blog/store-economics/how-much-is-a-shopify-store",
  "/blog/store-economics/shopify-profit-margin-calculator",
  "/blog/what-it-really-pays/average-income-of-a-business-owner",
  "/blog/what-it-really-pays/how-much-do-business-owners-make",
  "/blog/what-it-really-pays/how-much-do-businessmen-make-a-year",
  "/blog/what-it-really-pays/most-profitable-products-to-sell-online",
  "/blog/what-it-really-pays/statistics-about-small-businesses",
  "/blog/who-its-for/best-print-on-demand-site-for-artists",
  "/blog/who-its-for/best-print-on-demand-sites-for-beginners",
  "/blog/who-its-for/best-side-hustle-for-students",
  "/blog/who-its-for/dropshipping-for-beginners",
  "/blog/who-its-for/freelance-work-for-stay-at-home-moms",
  "/blog/who-its-for/freelance-writing-jobs-for-stay-at-home-moms",
  "/blog/who-its-for/how-to-make-money-online-for-beginner",
  "/blog/who-its-for/side-hustle-for-couples",
  "/blog/who-its-for/side-hustle-for-men",
  "/blog/who-its-for/side-hustle-for-nurse",
  "/blog/who-its-for/side-hustle-for-retirees",
  "/blog/who-its-for/side-hustle-for-single-moms",
  "/blog/who-its-for/side-hustle-for-stay-at-home-mom",
  "/blog/who-its-for/side-hustle-for-teachers",
  "/blog/who-its-for/side-hustle-for-teenager",
  "/blog/who-its-for/side-hustle-for-women",
  "/blog/who-its-for/ways-for-teenagers-to-make-money-online",
  "/blog/who-its-for/ways-to-make-money-online-for-women",
  "/blog/who-its-for/work-from-home-jobs-for-stay-at-home-moms",
];

export const RETIRED_REDIRECTS: Readonly<Record<string, string>> = {
  "/blog/ai-agencies/ai-agency-revenue": "/blog/ai-agencies/ai-agency-revenue-examples",
  "/blog/ai-agencies/ai-agent-for-business": "/blog/ai-agencies/ai-agents-that-make-money",
  "/blog/ai-agencies/ai-saas-revenue": "/blog/ai-agencies/is-ai-profitable",
  "/blog/ai-agencies/how-to-start-an-ai-agency": "/blog/ai-agencies/ai-agency-revenue-examples",
  "/blog/ai-agencies/what-is-an-ai-agency": "/blog/ai-agencies/ai-agency-revenue-examples",
  "/blog/ai-agencies/what-is-an-ai-agent": "/blog/ai-agencies/ai-agents-that-make-money",
  "/blog/ai-coding-tools/ai-coding-tools-revenue-ranked": "/blog/vibe-coding/vibe-coding-tools",
  "/blog/ai-coding-tools/claude-code-for-beginners": "/blog/ai-coding-tools/claude-code-examples",
  "/blog/ai-coding-tools/cursor-built-products": "/blog/built-with-ai/apps-built-with-cursor",
  "/blog/ai-coding-tools/lovable-built-products": "/blog/built-with-ai/apps-built-with-lovable",
  "/blog/ai-coding-tools/n8n-ai-agent-business": "/blog/built-with-ai/apps-built-with-n8n",
  "/blog/ai-coding-tools/replit-built-products": "/blog/built-with-ai/apps-built-with-replit",
  "/blog/app-revenue/app-monetization-models": "/blog/app-revenue/how-do-mobile-apps-make-money",
  "/blog/app-revenue/good-apps-to-make-money": "/blog/app-revenue/app-that-make-money",
  "/blog/app-revenue/how-do-free-mobile-apps-make-money": "/blog/app-revenue/how-do-mobile-apps-make-money",
  "/blog/app-revenue/how-much-does-app-development-cost": "/blog/app-revenue/how-much-does-it-cost-to-make-an-app",
  "/blog/blogs-and-affiliate/how-bloggers-make-money": "/blog/blogs-and-affiliate/niche-website-examples",
  "/blog/blogs-and-affiliate/how-much-can-a-blogger-make": "/blog/blogs-and-affiliate/niche-website-examples",
  "/blog/blogs-and-affiliate/how-to-earn-money-from-affiliate-marketing": "/blog/blogs-and-affiliate/affiliate-marketing-business-model",
  "/blog/blogs-and-affiliate/how-to-make-money-as-a-affiliate-marketer": "/blog/blogs-and-affiliate/affiliate-marketing-business-model",
  "/blog/blogs-and-affiliate/is-affiliate-marketing-worth-it": "/blog/blogs-and-affiliate/affiliate-marketing-business-model",
  "/blog/build-and-ship/how-to-make-a-chrome-extension": "/blog/build-and-ship/chrome-extension-revenue",
  "/blog/build-and-ship/no-code-app-builder": "/blog/build-and-ship/ai-app-builder",
  "/blog/build-and-ship/what-is-a-chrome-extension": "/blog/build-and-ship/chrome-extension-examples",
  "/blog/built-with-ai/100k-mrr": "/blog/built-with-ai/how-to-get-to-10k-mrr",
  "/blog/built-with-ai/apps-built-with-no-code-tools": "/blog/build-and-ship/no-code-saas-examples",
  "/blog/built-with-ai/best-ways-to-make-money-with-ai": "/blog/built-with-ai/how-to-make-money-with-ai",
  "/blog/built-with-ai/first-1000-mrr": "/blog/built-with-ai/how-to-get-to-10k-mrr",
  "/blog/built-with-ai/how-to-make-money-with-ai-for-free": "/blog/built-with-ai/how-to-make-money-with-ai",
  "/blog/built-with-ai/is-ai-profitable-yet": "/blog/ai-agencies/is-ai-profitable",
  "/blog/built-with-ai/using-ai-to-make-money": "/blog/built-with-ai/how-to-make-money-with-ai",
  "/blog/digital-products/digital-products-for-passive-income": "/blog/side-income/digital-products",
  "/blog/digital-products/digital-products-side-hustle": "/blog/side-income/digital-products",
  "/blog/digital-products/etsy-digital-products": "/blog/side-income/digital-products",
  "/blog/digital-products/etsy-for-selling-digital-products": "/blog/side-income/digital-products",
  "/blog/digital-products/how-to-make-money-on-substack": "/blog/digital-products/newsletter-business-model",
  "/blog/digital-products/sell-digital-products-online": "/blog/side-income/digital-products",
  "/blog/digital-products/shopify-digital-products": "/blog/side-income/digital-products",
  "/blog/digital-products/trending-and-relevant-app-ideas": "/blog/side-income/app-ideas-that-make-money",
  "/blog/digital-products/where-to-sell-digital-products": "/blog/side-income/digital-products",
  "/blog/launch-and-growth/product-market-fit": "/blog/launch-and-growth/how-to-validate-business-idea",
  "/blog/launch-and-growth/saas-pricing": "/blog/saas-metrics/tiered-pricing-examples",
  "/blog/platform-guides/how-to-create-an-app": "/blog/vibe-coding/how-to-vibe-code",
  "/blog/platform-guides/how-to-make-money-online-youtube": "/blog/side-income/faceless-youtube-channel-revenue",
  "/blog/platform-guides/how-to-make-youtube-channel-to-make-money": "/blog/side-income/faceless-youtube-channel-revenue",
  "/blog/revenue-reality/most-profitable-businesses": "/blog/startup-ideas/business-model-examples",
  "/blog/risks-and-rules/legit-side-hustle": "/blog/side-income/ai-side-hustle",
  "/blog/risks-and-rules/percentage-of-business-that-fail": "/blog/risks-and-rules/why-do-business-fail",
  "/blog/risks-and-rules/what-percent-of-business-fail": "/blog/risks-and-rules/why-do-business-fail",
  "/blog/risks-and-rules/why-do-small-business-fail": "/blog/risks-and-rules/why-do-business-fail",
  "/blog/saas-metrics/arpu-meaning": "/blog/saas-metrics/saas-metrics-founders-track",
  "/blog/saas-metrics/b2b-saas-meaning": "/blog/saas-metrics/saas-business-models",
  "/blog/saas-metrics/cac-meaning": "/blog/saas-metrics/saas-metrics-founders-track",
  "/blog/saas-metrics/churn-meaning": "/blog/saas-metrics/saas-metrics-founders-track",
  "/blog/saas-metrics/examples-of-saas-companies": "/blog/saas-metrics/micro-saas-examples-with-revenue",
  "/blog/saas-metrics/how-to-reduce-churn": "/blog/saas-metrics/saas-metrics-founders-track",
  "/blog/saas-metrics/ltv-meaning": "/blog/saas-metrics/saas-metrics-founders-track",
  "/blog/saas-metrics/payback-period": "/blog/saas-metrics/saas-metrics-founders-track",
  "/blog/saas-metrics/saas-examples-with-revenue": "/blog/saas-metrics/micro-saas-examples-with-revenue",
  "/blog/saas-metrics/unit-economics": "/blog/saas-metrics/saas-metrics-founders-track",
  "/blog/saas-metrics/what-does-saas-stand-for": "/blog/saas-metrics/saas-business-models",
  "/blog/saas-metrics/what-is-a-saas-company": "/blog/saas-metrics/saas-business-models",
  "/blog/saas-metrics/what-is-saas": "/blog/saas-metrics/saas-business-models",
  "/blog/shop-operations/affiliate-marketing-side-hustle": "/blog/blogs-and-affiliate/affiliate-marketing-business-model",
  "/blog/side-income/app-ideas": "/blog/side-income/app-ideas-that-make-money",
  "/blog/side-income/how-to-create-digital-products": "/blog/side-income/digital-products",
  "/blog/side-income/how-to-sell-digital-products": "/blog/side-income/digital-products",
  "/blog/side-income/most-profitable-digital-products": "/blog/side-income/digital-products",
  "/blog/side-income/most-profitable-side-hustles": "/blog/side-income/ai-side-hustle",
  "/blog/side-income/side-hustles-to-earn-extra-money": "/blog/side-income/ai-side-hustle",
  "/blog/side-income/side-hustles-to-make-money": "/blog/side-income/ai-side-hustle",
  "/blog/solo-founders/bootstrapped-startup-reality": "/blog/solo-founders/bootstrapped-meaning",
  "/blog/solo-founders/one-person-company": "/blog/solo-founders/solopreneur-income",
  "/blog/solo-founders/programmer-income": "/blog/solo-founders/solopreneur-income",
  "/blog/start-cheap/ideas-of-online-business-at-home": "/blog/startup-ideas/online-business-examples",
  "/blog/start-cheap/low-cost-business-ideas": "/blog/startup-ideas/low-cost-business-ideas",
  "/blog/start-cheap/online-business-ideas-without-investment": "/blog/startup-ideas/low-cost-business-ideas",
  "/blog/start-cheap/online-side-hustle-from-home": "/blog/side-income/ai-side-hustle",
  "/blog/start-cheap/quick-side-hustle": "/blog/side-income/ai-side-hustle",
  "/blog/start-cheap/side-hustle-from-home": "/blog/side-income/ai-side-hustle",
  "/blog/start-cheap/side-hustle-ideas-from-home": "/blog/side-income/ai-side-hustle",
  "/blog/start-cheap/small-business-ideas-from-home": "/blog/startup-ideas/best-small-business-to-start",
  "/blog/startup-ideas/app-ideas": "/blog/side-income/app-ideas-that-make-money",
  "/blog/startup-ideas/best-online-side-hustle": "/blog/side-income/ai-side-hustle",
  "/blog/startup-ideas/business-ideas-for-online-services": "/blog/startup-ideas/service-business-examples",
  "/blog/startup-ideas/e-commerce-examples": "/blog/built-with-ai/shopify-stores-and-apps-built-with-ai",
  "/blog/startup-ideas/ecommerce-business-ideas": "/blog/built-with-ai/shopify-stores-and-apps-built-with-ai",
  "/blog/startup-ideas/good-online-business-ideas": "/blog/startup-ideas/online-business-examples",
  "/blog/startup-ideas/ideas-online-business": "/blog/startup-ideas/online-business-examples",
  "/blog/startup-ideas/mobile-app-ideas": "/blog/side-income/app-ideas-that-make-money",
  "/blog/startup-ideas/most-lucrative-side-hustle": "/blog/side-income/ai-side-hustle",
  "/blog/startup-ideas/most-successful-small-business-ideas": "/blog/startup-ideas/best-small-business-to-start",
  "/blog/startup-ideas/online-store-business-ideas": "/blog/built-with-ai/shopify-stores-and-apps-built-with-ai",
  "/blog/startup-ideas/small-business-ideas": "/blog/startup-ideas/best-small-business-to-start",
  "/blog/store-economics/examples-of-shopify-stores": "/blog/built-with-ai/shopify-stores-and-apps-built-with-ai",
  "/blog/store-economics/how-to-earn-money-from-shopify": "/blog/built-with-ai/shopify-stores-and-apps-built-with-ai",
  "/blog/store-economics/how-to-make-money-using-shopify": "/blog/built-with-ai/shopify-stores-and-apps-built-with-ai",
  "/blog/vibe-coding/vibe-coding-examples": "/blog/vibe-coding/vibe-coded-apps",
  "/blog/vibe-coding/vibe-coding-worth-it": "/blog/vibe-coding/vibe-coding",
  "/blog/vibe-coding/what-is-vibe-coding": "/blog/vibe-coding/vibe-coding",
  "/blog/what-it-really-pays/boring-business-that-make-money": "/blog/startup-ideas/niche-business-ideas",
  "/blog/what-it-really-pays/business-ideas-that-are-profitable": "/blog/startup-ideas/business-model-examples",
  "/blog/what-it-really-pays/highest-profit-margin-business": "/blog/startup-ideas/business-model-examples",
  "/blog/what-it-really-pays/how-much-does-it-cost-to-start-a-business": "/blog/startup-ideas/low-cost-business-ideas",
  "/blog/what-it-really-pays/how-much-money-do-you-need-to-start-a-business": "/blog/startup-ideas/low-cost-business-ideas",
  "/blog/what-it-really-pays/make-money-on-websites": "/blog/blogs-and-affiliate/niche-website-examples",
  "/blog/what-it-really-pays/online-websites-to-make-money": "/blog/blogs-and-affiliate/niche-website-examples",
  "/blog/what-it-really-pays/what-business-is-most-profitable": "/blog/startup-ideas/business-model-examples",
  "/blog/what-it-really-pays/youtube-channel-income": "/blog/side-income/faceless-youtube-channel-revenue",
  "/blog/what-it-really-pays/youtube-channel-revenue-estimator": "/blog/side-income/faceless-youtube-channel-revenue",
  "/blog/who-its-for/home-business-for-stay-at-home-moms": "/blog/startup-ideas/best-small-business-to-start",
  "/blog/who-its-for/online-business-ideas-for-beginners": "/blog/startup-ideas/online-business-examples",
  "/blog/who-its-for/small-business-ideas-for-women": "/blog/startup-ideas/best-small-business-to-start",
  "/blog/who-its-for/stay-at-home-business-ideas-for-moms": "/blog/startup-ideas/best-small-business-to-start",
};

export const REMOVED_CATEGORIES: readonly string[] = ["who-its-for", "platform-guides", "shop-operations", "print-on-demand", "physical-products", "start-cheap", "store-economics", "what-it-really-pays"];

const goneSet = new Set(RETIRED_GONE);
const removedCatSet = new Set(REMOVED_CATEGORIES);

/** 这个路径该返回 410 吗(已删文章,或已撤分类下没有合并去处的任何地址)。 */
export function isRetiredGone(pathname: string): boolean {
  const p = pathname.length > 1 ? pathname.replace(/\/+$/, "") : pathname;
  if (goneSet.has(p)) return true;
  const m = p.match(/^\/blog\/([^/]+)(?:\/[^/]+)?$/);
  return !!m && removedCatSet.has(m[1]) && !(p in RETIRED_REDIRECTS);
}
